baseURL = "http://example.org/"
languageCode = "en-us"
title = "Andrew Baker"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
    author = "Andrew Baker"
    description = "Ramblings of a System Administrator"
      menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/andrewbaker-uk"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/andrewbaker4"
