baseURL = "https://www.andrewbaker.uk"
languageCode = "en-us"
title = "Andrew Baker Blog"
theme = "ananke"
publishDir = "public"


SectionPagesMenu = "main"

[params]
  favicon = ""
  site_logo = ""
  description = "The blog of Andrew Baker"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/andrewbaker-uk"
  gitlab = ""
  linkedin = "https://linkedin.com/in/andrewbaker4"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  featured_image = ""
  recent_posts_number = 2